routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('bank-branches/fetch-banks', 'BankBranchesController@fetch_banks');
Route::get('accounts/fetch-bank-branches', 'AccountController@fetch_bank_branches');
Route::get('branches/fetch-company-branches', 'BranchController@fetch_company_branches');
Route::get('holiday-maintenance/fetch-holidays', 'HolidayCalendarController@fetch_holidays');

Route::get('cheques/queue', 'ChequesInQueueController@index')->name('cheques.queue.index');
Route::get('cheques/load-to-queue', 'ChequesInQueueController@load_to_queue');
Route::post('cheques/load-next-to-queue', 'ChequesInQueueController@load_next_to_queue');
Route::post('cheques/load-prev-to-queue', 'ChequesInQueueController@load_prev_to_queue');
Route::get('cheques/load-cheque-from-select', 'ChequesInQueueController@load_cheque_from_select');
Route::post('cheques/save-cheques-in-queue', 'ChequesInQueueController@save_cheques_in_queue');
Route::post('cheques/save-ciq-field-value', 'ChequesInQueueController@save_ciq_field_value');
Route::post('cheques/remove-cheque-from-queue', 'ChequesInQueueController@remove_cheque_from_queue');
Route::get('cheques/get-values-for-setting-queue-default-type', 'ChequesInQueueController@get_values_for_setting_queue_default_type');
Route::post('cheques/set-queue-default', 'ChequesInQueueController@set_queue_default');

Route::get('cheques/hand', 'ChequesInHandController@index')->name('cheques.hand.index');
Route::get('cheques/hand-hold', 'ChequesInHandController@on_hold_cheques')->name('cheques.hand-hold.index');
Route::post('cheques/select-cheques-in-hand', 'ChequesInHandController@select_cheques_in_hand');
Route::get('cheques/hold-cheque', 'ChequesInHandController@hold_cheque');
Route::get('cheques/release-cheque', 'ChequesInHandController@release_cheque');
Route::get('cheques/hold-selected-cheques', 'ChequesInHandController@hold_selected_cheques');
Route::get('cheques/release-selected-cheques', 'ChequesInHandController@release_selected_cheques');
Route::get('cheques/show-cheque-image', 'ChequesInHandController@show_cheque_image');

Route::get('cheques/grant-cheques', 'GrantChequesController@grant_cheques');
Route::post('cheques/load-selected-cheque-in-grant-queue', 'GrantChequesController@load_selected_cheque_in_grant_queue');
Route::post('cheques/submit-grant-cheques', 'GrantChequesController@submit_grant_cheques');

Route::get('cheques/banks', 'ChequesToBankController@index')->name('cheques.bank.index');
Route::get('cheques/bank-return', 'ChequesToBankController@return_cheques')->name('cheques.bank-return.index');
Route::get('cheques/mark-return', 'ChequesToBankController@mark_return');
Route::post('cheques/submit-return-cheques', 'ChequesToBankController@submit_return_cheques');

Route::get('cheques/vendors', 'ChequesToVendorController@index')->name('cheques.vendor.index');

Route::get('cheques/scanned', 'ScannedChequesController@index')->name('cheques.scanned.index');
Route::get('cheques/scanned/show-cheque-image', 'ScannedChequesController@show_cheque_image');

Route::resource('banks', 'BanksController');
Route::resource('bank-branches', 'BankBranchesController');
Route::resource('branches', 'BranchController');
Route::resource('return-reasons', 'ReturnReasonController');
Route::resource('vendors', 'VendorController');
Route::resource('accounts', 'AccountController');
Route::resource('holiday-maintenance', 'HolidayCalendarController');

Route::get('reports', 'ReportsController@index')->name('reports.index');
Route::post('reports/generate', 'ReportsController@generate')->name('reports.generate');
Route::get('reports/get-customer', 'ReportsController@get_customer');
Route::post('reports/validate-input', 'ReportsController@validate_input')->name('reports.input_validity');
Route::get('/customer/print-pdf', 'ReportsController@printpdf')->name('reports.printpdf');

Route::post('sys-date/update', 'SystemDateController@update')->name('sys-date.update');
Route::post('sys-date/undo', 'SystemDateController@undo')->name('sys-date.undo');
Route::post('home/open_scanner', 'HomeController@open_scanner')->name('open_scanner');

app/ReturnReason.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ReturnReason extends Model
{
}

app/Http/Controllers/ReturnReasonController.php
<?php

namespace App\Http\Controllers;

use App\ReturnReason;
use Illuminate\Http\Request;

use DataTables;

class ReturnReasonController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $pageTitle = 'Return Reasons';
        $return_reasons = ReturnReason::where('is_deleted', '0')->get();
        $sys_date = Controller::get_system_date();

        if ($request->ajax()) {
            $return_reasons = ReturnReason::where('is_deleted', '0')->get();
            return DataTables::of($return_reasons)
                ->addColumn('action', function ($return_reasons) {
                    $button =  '<button type="button" class="btn btn-info btn-min-width dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Action</button>
                                    <div class="dropdown-menu" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -141px, 0px);">
                                        <button class="dropdown-item" onclick="edit_record(' . $return_reasons->id . ')">Edit</button>
                                        <button class="dropdown-item" onclick="remove_record(' . $return_reasons->id . ')">Remove</button>
                                    </div>';

                    return $button;
                })
                ->rawColumns(['action'])
                ->make('true');
        }

        return view('return_reasons.index', compact('pageTitle', 'return_reasons', 'sys_date'));
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {

        if ($request->title == '') {
            $output = json_encode(array('type' => 'error', 'text' => 'Title cannot be empty'));
            die($output);
        }

        if ($request->code == '') {
            $output = json_encode(array('type' => 'error', 'text' => 'Code cannot be empty'));
            die($output);
        }

        $returnReason               = new ReturnReason;

        $returnReason->title         = $request->title;
        $returnReason->code         = $request->code;

        // $bank->save();
        if ($returnReason->save()) {
            $output = json_encode(array('type' => 'success', 'text' => 'Return Reason added successfully'));
            die($output);
        } else {
            $output = json_encode(array('type' => 'error', 'text' => 'Unkown error occurred. Please try again later'));
            die($output);
        }
    }


    public function show(ReturnReason $returnReason)
    {
        //
    }


    public function edit(ReturnReason $returnReason)
    {
        return $returnReason;
    }


    public function update(Request $request, ReturnReason $returnReason)
    {

        if ($request->title == '') {
            $output = json_encode(array('type' => 'error', 'text' => 'Title cannot be empty'));
            die($output);
        }

        if ($request->code == '') {
            $output = json_encode(array('type' => 'error', 'text' => 'Code cannot be empty'));
            die($output);
        }

        $returnReason->title         = $request->title;
        $returnReason->code         = $request->code;

        // $bank->save();
        if ($returnReason->save()) {
            $output = json_encode(array('type' => 'success', 'text' => 'Return Reason updated successfully'));
            die($output);
        } else {
            $output = json_encode(array('type' => 'error', 'text' => 'Unkown error occurred. Please try again later'));
            die($output);
        }
    }


    public function destroy(ReturnReason $returnReason)
    {

        $returnReason->is_deleted = '1';

        if ($returnReason->save()) {
            $output = json_encode(array('type' => 'success', 'text' => 'Return Reason removed successfully'));
            die($output);
        } else {
            $output = json_encode(array('type' => 'error', 'text' => 'Unkown error occurred. Please try again later'));
            die($output);
        }
    }
}

resources/views/return_reasons/index.blade.php
@extends('layouts.app')

@section('page_css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/extensions/responsive.dataTables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/extensions/buttons.dataTables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">


@endsection

@section('content')
 <div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
                <h3 class="content-header-title mb-0 d-inline-block">Manage Return Reasons</h3>
                <div class="row breadcrumbs-top d-inline-block">
                <div class="breadcrumb-wrapper col-12">
                    <ol class="breadcrumb">
                    <li class="breadcrumb-item">Add, Update or Delete Return Reasons
                    </li>
                    </ol>
                </div>
                </div>
            </div>
        </div>
        <div class="content-body"><!-- Revenue, Hit Rate & Deals -->
            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">All Return Reasons</h4>
                                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <button type="button" class="btn btn-info btn-min-width btn-glow btn-cons pull-right" data-toggle="modal" data-target="#createReturnReason">
										Add
                                    </button>
                                    <div class="modal fade text-left" id="createReturnReason" role="dialog" aria-labelledby="createReturnReasonModal" aria-hidden="true">
										<div class="modal-dialog modal-lg" role="document">
											<div class="modal-content">
												<div class="modal-header">
													<label class="modal-title text-text-bold-600" id="createReturnReasonModal">Create Branch</label>
													<button type="button" class="close" data-dismiss="modal" aria-label="Close">
													  <span aria-hidden="true">&times;</span>
													</button>
												</div>
												<form class="add_bank_form">
											  	  <div class="modal-body">
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <fieldset class="form-group form-group-style">
                                                                    <label for="title">Title <span class="red">*</span></label>
                                                                    <input type="text" class="form-control return_reasons" id="title" >
                                                                </fieldset>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <fieldset class="form-group form-group-style">
                                                                    <label for="code">Code <span class="red">*</span></label>
                                                                    <input type="text" class="form-control return_reasons" id="code" >
                                                                </fieldset>
                                                            </div>
                                                        </div>
												  </div>
												  <div class="modal-footer">
													<button type="reset" class="btn btn-secondary btn-glow" data-dismiss="modal" >Close</button>
													<button type="button" id="submit_rr" class="btn btn-success btn-glow"> Save </button>
												  </div>
												</form>
											</div>
										</div>
									</div>
                                </div>
                            </div>
                            <div class="card-content collapse show">
                                <div class="card-body card-dashboard">
                                    <table class="table table-striped table-bordered" id="return_reasons_list">
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Code</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
  </div>

    <div class="modal fade text-left" id="editReturnReason" role="dialog" aria-labelledby="editReturnReasonModal" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <label class="modal-title text-text-bold-600" id="editReturnReasonModal">Edit Bank Branch</label>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="edit_bank_form">
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                <fieldset class="form-group form-group-style">
                                    <label for="edit_title">Title <span class="red">*</span></label>
                                    <input type="text" class="form-control return_reasons" id="edit_title" >
                                    <input type="hidden" class="form-control return_reasons" id="edit_id" >
                                </fieldset>
                            </div>
                            <div class="col-md-6">
                                <fieldset class="form-group form-group-style">
                                    <label for="edit_code">Code <span class="red">*</span></label>
                                    <input type="text" class="form-control return_reasons" id="edit_code" >
                                </fieldset>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary btn-glow" data-dismiss="modal" >Close</button>
                    <button type="button" id="update_rr" class="btn btn-success btn-glow"> Update </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('page_js')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/buttons.colVis.min.js') }}"></script>

<script>
    var table = $('#return_reasons_list').DataTable({
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{ route('return-reasons.index') }}"
        },
        columns: [
            {
                data: 'title',
                name: 'title'
            },
            {
                data: 'code',
                name: 'code'
            },
            {
                data: 'action',
                name: 'action',
                orderable: false
            }
        ],
        responsive: true,
        dom: 'Bfrtip',
        stateSave: true,
        buttons: [
            'colvis'
        ]
    });

    $('#submit_rr').on('click',function() {
        $('#submit_rr').html('<i class="la la-circle-o-notch spinner"></i> Loading...');
        $('#submit_rr').attr('disabled', 'true');

        var data = {
            'title' : $("#title").val(),
            'code' : $("#code").val()
        };

        $.ajax({
            type: "POST",
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: '{{ route("return-reasons.store") }}',
            data: data,
            dataType: "json",
            success: function(response) {
                if(response.type == 'success') {
                    toastr.success(response.text);

                    $('#submit_rr').html('Save');
                    $('#submit_rr').removeAttr('disabled');

                    $("#title").val('');
                    $("#code").val('');

                    setTimeout(function(){ 
                        $('#createReturnReason').modal('hide');

                        table.ajax.reload();
                    }, 1000);
                    
                } else if (response.type == 'error') {
                    toastr.error(response.text);
                    $('#submit_rr').html('Save');
                    $('#submit_rr').removeAttr('disabled');
                } else {
                    toastr.warning("Couldn't complete the request. Please contact management");
                    $('#submit_rr').html('Save');
                    $('#submit_rr').removeAttr('disabled');
                }
            },
            error:  function(response) {
                toastr.warning("Couldn't complete the request. Please contact management");
                $('#submit_rr').html('Save');
                $('#submit_rr').removeAttr('disabled');
            }
        });

    });

    $('#update_rr').on('click',function() {
        $('#update_rr').html('<i class="la la-circle-o-notch spinner"></i> Loading...');
        $('#update_rr').attr('disabled', 'true');

        id =  $("#edit_id").val();

        var data = {
            'title' : $("#edit_title").val(),
            'code' : $("#edit_code").val()
        };

        $.ajax({
            type: "PUT",
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: 'return-reasons/'+id,
            data: data,
            dataType: "json",
            success: function(response) {
                if(response.type == 'success') {

                    toastr.success(response.text);
                    table.ajax.reload();
                    
                } else if (response.type == 'error') {

                    toastr.error(response.text);
                    
                } else {

                    toastr.warning("Couldn't complete the request. Please contact management");
                    
                }

                $('#update_rr').html('Update');
                $('#update_rr').removeAttr('disabled');
            },
            error:  function(response) {
                toastr.warning("Couldn't complete the request. Please contact management");
                
                $('#update_rr').html('Update');
                $('#update_rr').removeAttr('disabled');
            }
        });

    });


    function edit_record(id) {
        $.ajax({
            type: "GET",
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: 'return-reasons/'+id+'/edit',
            dataType: "json",
            success: function(response) {

                $("#edit_id").val(response.id);
                $("#edit_title").val(response.title);
                $("#edit_code").val(response.code);

                $('#editReturnReason').modal('show');

            },
            error:  function(response) {
                toastr.warning("Couldn't complete the request. Please contact management");
            }
        });
    }

    function remove_record(id) {
        $.ajax({
            type: "DELETE",
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: 'return-reasons/'+id,
            dataType: "json",
            success: function(response) {
                if(response.type == 'success') {
                    toastr.success(response.text);

                    table.ajax.reload();
                    
                } else if (response.type == 'error') {
                    toastr.error(response.text);
                    
                } else {
                    toastr.warning("Couldn't complete the request. Please contact management");
                    
                }
            },
            error:  function(response) {
                toastr.warning("Couldn't complete the request. Please contact management");
            }
        });
    }

</script>
@endsection