routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('bank-branches/fetch-banks', 'BankBranchesController@fetch_banks');
Route::get('accounts/fetch-bank-branches', 'AccountController@fetch_bank_branches');
Route::get('branches/fetch-company-branches', 'BranchController@fetch_company_branches');
Route::get('holiday-maintenance/fetch-holidays', 'HolidayCalendarController@fetch_holidays');

Route::get('cheques/queue', 'ChequesInQueueController@index')->name('cheques.queue.index');
Route::get('cheques/load-to-queue', 'ChequesInQueueController@load_to_queue');
Route::post('cheques/load-next-to-queue', 'ChequesInQueueController@load_next_to_queue');
Route::post('cheques/load-prev-to-queue', 'ChequesInQueueController@load_prev_to_queue');
Route::get('cheques/load-cheque-from-select', 'ChequesInQueueController@load_cheque_from_select');
Route::post('cheques/save-cheques-in-queue', 'ChequesInQueueController@save_cheques_in_queue');
Route::post('cheques/save-ciq-field-value', 'ChequesInQueueController@save_ciq_field_value');
Route::post('cheques/remove-cheque-from-queue', 'ChequesInQueueController@remove_cheque_from_queue');
Route::get('cheques/get-values-for-setting-queue-default-type', 'ChequesInQueueController@get_values_for_setting_queue_default_type');
Route::post('cheques/set-queue-default', 'ChequesInQueueController@set_queue_default');

Route::get('cheques/hand', 'ChequesInHandController@index')->name('cheques.hand.index');
Route::get('cheques/hand-hold', 'ChequesInHandController@on_hold_cheques')->name('cheques.hand-hold.index');
Route::post('cheques/select-cheques-in-hand', 'ChequesInHandController@select_cheques_in_hand');
Route::get('cheques/hold-cheque', 'ChequesInHandController@hold_cheque');
Route::get('cheques/release-cheque', 'ChequesInHandController@release_cheque');
Route::get('cheques/hold-selected-cheques', 'ChequesInHandController@hold_selected_cheques');
Route::get('cheques/release-selected-cheques', 'ChequesInHandController@release_selected_cheques');
Route::get('cheques/show-cheque-image', 'ChequesInHandController@show_cheque_image');

Route::get('cheques/grant-cheques', 'GrantChequesController@grant_cheques');
Route::post('cheques/load-selected-cheque-in-grant-queue', 'GrantChequesController@load_selected_cheque_in_grant_queue');
Route::post('cheques/submit-grant-cheques', 'GrantChequesController@submit_grant_cheques');

Route::get('cheques/banks', 'ChequesToBankController@index')->name('cheques.bank.index');
Route::get('cheques/bank-return', 'ChequesToBankController@return_cheques')->name('cheques.bank-return.index');
Route::get('cheques/mark-return', 'ChequesToBankController@mark_return');
Route::post('cheques/submit-return-cheques', 'ChequesToBankController@submit_return_cheques');

Route::get('cheques/vendors', 'ChequesToVendorController@index')->name('cheques.vendor.index');

Route::get('cheques/scanned', 'ScannedChequesController@index')->name('cheques.scanned.index');
Route::get('cheques/scanned/show-cheque-image', 'ScannedChequesController@show_cheque_image');

Route::resource('banks', 'BanksController');
Route::resource('bank-branches', 'BankBranchesController');
Route::resource('branches', 'BranchController');
Route::resource('return-reasons', 'ReturnReasonController');
Route::resource('vendors', 'VendorController');
Route::resource('accounts', 'AccountController');
Route::resource('holiday-maintenance', 'HolidayCalendarController');

Route::get('reports', 'ReportsController@index')->name('reports.index');
Route::post('reports/generate', 'ReportsController@generate')->name('reports.generate');
Route::get('reports/get-customer', 'ReportsController@get_customer');
Route::post('reports/validate-input', 'ReportsController@validate_input')->name('reports.input_validity');
Route::get('/customer/print-pdf', 'ReportsController@printpdf')->name('reports.printpdf');

Route::post('sys-date/update', 'SystemDateController@update')->name('sys-date.update');
Route::post('sys-date/undo', 'SystemDateController@undo')->name('sys-date.undo');
Route::post('home/open_scanner', 'HomeController@open_scanner')->name('open_scanner');

resources/views/include/footer_scripts.blade.php
<!-- BEGIN VENDOR JS-->
    <script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{{ asset('app-assets/vendors/js/ui/jquery.sticky.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/charts/chart.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/charts/raphael-min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/charts/morris.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/charts/jvector/jquery-jvectormap-2.0.3.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/charts/jvector/jquery-jvectormap-world-mill.js') }}"></script>
    <script src="{{ asset('app-assets/data/jvector/visitor-data.js') }}"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN MODERN JS-->
    <script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
    <script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
    <script src="{{ asset('app-assets/js/core/app.js') }}"></script>
    <!-- END MODERN JS-->

    <script>
        $('#eod_update').click(function () {
            
            $('#eod_update').html('<i class="la la-circle-o-notch spinner"></i> Ending Day Process...');
            $('#eod_update').attr('disabled', 'true');

            var data = {
                'sys_date' : $("#sys_date").val(),
            };

            $.ajax({
                type: "POST",
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                url: '{{ route("sys-date.update") }}',
                data: data,
                dataType: "json",
                success: function(response) {
                    if(response.type == 'success') {
                        toastr.success(response.text);

                        $('#eod_update').html('End Day Process');
                        $('#eod_update').removeAttr('disabled');

                        $("#sys_date").val(response.sys_date);

                        setTimeout(function(){ 
                            location.reload();
                        }, 1000);
                        
                    } else if (response.type == 'error') {
                        toastr.error(response.text);
                        $('#eod_update').html('End Day Process');
                        $('#eod_update').removeAttr('disabled');
                    } else {
                        toastr.warning("Couldn't complete the request. Please contact management");
                        $('#eod_update').html('End Day Process');
                        $('#eod_update').removeAttr('disabled');
                    }
                },
                error:  function(response) {
                    toastr.warning("Couldn't complete the request. Please contact management");
                    $('#eod_update').html('End Day Process');
                    $('#eod_update').removeAttr('disabled');
                }
            });
        });

        $('#open_scanner').click(function() {

            $.ajax({
                type: "POST",
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                url: '{{ route("open_scanner") }}',
                dataType: "json",
                success: function(response) {
                }
            });
        });

        
        $('#eod_undo').click(function () {
            
            $('#eod_undo').html('<i class="la la-circle-o-notch spinner"></i> Undoing End Day Process...');
            $('#eod_undo').attr('disabled', 'true');

            var data = {
                'sys_date' : $("#sys_date").val(),
            };

            $.ajax({
                type: "POST",
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                url: '{{ route("sys-date.undo") }}',
                data: data,
                dataType: "json",
                success: function(response) {
                    if(response.type == 'success') {
                        toastr.success(response.text);

                        $('#eod_undo').html('Undo');
                        $('#eod_undo').removeAttr('disabled');

                        $("#sys_date").val(response.sys_date);
                        setTimeout(function(){ 
                            location.reload();
                        }, 1000);
                        
                    } else if (response.type == 'error') {
                        toastr.error(response.text);
                        $('#eod_undo').html('Undo');
                        $('#eod_undo').removeAttr('disabled');
                    } else {
                        toastr.warning("Couldn't complete the request. Please contact management");
                        $('#eod_undo').html('Undo');
                        $('#eod_undo').removeAttr('disabled');
                    }
                },
                error:  function(response) {
                    toastr.warning("Couldn't complete the request. Please contact management");
                    $('#eod_undo').html('Undo');
                    $('#eod_undo').removeAttr('disabled');
                }
            });
        });
    </script>

resources/views/include/header_styles.blade.php
<!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/vendors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.css') }}">
    <!-- END VENDOR CSS-->
    <!-- BEGIN MODERN CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/app.css') }}">
    <!-- END MODERN CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/core/menu/menu-types/horizontal-menu.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/core/colors/palette-gradient.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/charts/jquery-jvectormap-2.0.3.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/charts/morris.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/fonts/simple-line-icons/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/core/colors/palette-gradient.css') }}">
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css') }}">
    <!-- END Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/toastr.min.css') }}">

resources/views/include/sidenav.blade.php
<div class="header-navbar navbar-expand-sm navbar navbar-horizontal navbar-fixed navbar-dark navbar-without-dd-arrow navbar-shadow" role="navigation" data-menu="menu-wrapper">

      <div class="navbar-container main-menu-content" data-menu="menu-container">
        <ul class="nav navbar-nav" id="main-menu-navigation" data-menu="menu-navigation">
          <li class=" nav-item {{ $pageTitle == 'Home' ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('home') }}"><i class="la la-dashboard"></i><span class="menu-title">Dashboard</span></a>
          </li>
          <li data-menu="dropdown" class="dropdown nav-item 
          {{ $pageTitle == 'Cheques in Queue' || 
          $pageTitle == 'Cheques in Hand' || 
          $pageTitle == 'Cheques to Bank' || 
          $pageTitle == 'Cheques to Vendor' ? 'active' : '' 
          }}"><a class="dropdown-toggle nav-link" href="#"><i class="la la-money"></i><span class="menu-title">Cheques</span></a>
            <ul class="dropdown-menu">
              <li class="{{ $pageTitle == 'Cheques in Queue' ? 'active' : ''}}"><a class="dropdown-item" href="{{ route('cheques.queue.index') }}">Cheques in Queue</a>
              </li>
              <li class="{{ $pageTitle == 'Cheques in Hand' ? 'active' : ''}}"><a class="dropdown-item" href="{{ route('cheques.hand.index') }}">Cheques in Hand</a>
              </li>
              <li class="{{ $pageTitle == 'Cheques to Bank' ? 'active' : ''}}"><a class="dropdown-item" href="{{ route('cheques.bank.index') }}">Cheques to Bank</a>
              </li>
              <li class="{{ $pageTitle == 'Cheques to Vendor' ? 'active' : ''}}"><a class="dropdown-item" href="{{ route('cheques.vendor.index') }}">Cheques to Vendor</a>
              </li>
              <li class="{{ $pageTitle == 'Scanned Cheques' ? 'active' : ''}}"><a class="dropdown-item" href="{{ route('cheques.scanned.index') }}">Scanned Cheques</a>
              </li>
            </ul>
          </li>
          <li data-menu="dropdown" class="dropdown nav-item
          {{ $pageTitle == 'Banks' || $pageTitle == 'Bank Branches' ? 'active' : '' }}">
          <a class="dropdown-toggle nav-link" href="#"><i class="la la-bank"></i><span class="menu-title">Banks</span></a>
            <ul class="dropdown-menu">
              <li class="{{ $pageTitle == 'Banks' ? 'active' : ''}}"><a class="dropdown-item" href="{{ route('banks.index') }}">Banks</a>
              </li>
              <li class="{{ $pageTitle == 'Bank Branches' ? 'active' : ''}}"><a class="dropdown-item" href="{{ route('bank-branches.index') }}">Banks Branches</a>
              </li>
            </ul>
          </li>
          <li class=" nav-item {{ $pageTitle == 'Branches' ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('branches.index') }}"><i class="la la-sitemap"></i><span class="menu-title">Branches</span></a>
          </li>
          <li class=" nav-item {{ $pageTitle == 'Accounts' ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('accounts.index') }}"><i class="la la-folder-open"></i><span class="menu-title">Accounts</span></a>
          </li>
          <li class=" nav-item {{ $pageTitle == 'Return Reasons' ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('return-reasons.index') }}"><i class="la la-step-backward"></i><span class="menu-title">Return Reasons</span></a>
          </li>
          <li class=" nav-item {{ $pageTitle == 'Holiday Maintenance' ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('holiday-maintenance.index') }}"><i class="la la-calendar"></i><span class="menu-title">Holiday Maintenance</span></a>
          </li>
          <li class=" nav-item {{ $pageTitle == 'Vendors' ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('vendors.index') }}"><i class="la la-group"></i><span class="menu-title">Vendors</span></a>
          </li>
          <li class=" nav-item {{ $pageTitle == 'Reports' ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('reports.index') }}"><i class="la la-print"></i><span class="menu-title">Reports</span></a>
          </li>
        </ul>
      </div>
</div>

resources/views/include/topbar.blade.php
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow navbar-static-top navbar-light navbar-brand-center">
  <div class="navbar-wrapper">
        <div class="navbar-header">
          <ul class="nav navbar-nav flex-row position-relative">
            <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
            <li class="nav-item mr-auto"><a class="navbar-brand" href="index.html"><img class="brand-logo" alt="modern admin logo" src="{{ asset('app-assets/images/logo/logo.png') }}">
                <h3 class="brand-text">{{ config('app.name') }}</h3></a></li>
            <li class="nav-item d-none d-md-block nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="toggle-icon ft-toggle-right font-medium-3 white" data-ticon="ft-toggle-right"></i></a></li>
            <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a></li>
          </ul>
        </div>
        <div class="navbar-container content">
          <div class="collapse navbar-collapse" id="navbar-mobile">
            <ul class="nav navbar-nav mr-auto float-left">         
              <li class="dropdown nav-item mega-dropdown"><a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">System Date</a>
                <ul class="mega-dropdown-menu dropdown-menu row col-md-4">
                  <li class="col-md-12">
                    <h6 class="dropdown-menu-header text-uppercase mb-1"><i class="la la-calendar-o"></i> System Date</h6>
                    <div>
                      <fieldset class="form-group form-group-style">
                        <input disabled value="{{ $sys_date }}" type="date" class="form-control" id="sys_date" >
                      </fieldset>
                      <div class="float-right">
                        <button type="button" id="eod_update" class="btn btn-info btn-small"> End Day Process </button>
                        {{-- <button type="button" id="eod_undo" class="btn btn-secondary btn-small"> Undo </button> --}}
                      </div>
                    </div>
                  </li>
                  
            
                </ul>
              </li>        
              <li class="nav-item"><a id="open_scanner" class="nav-link" >Launch Scanner</a>
              </li>
            </ul>
            <ul class="nav navbar-nav float-right">
              <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown"><span class="mr-1">Hello,<span class="user-name text-bold-700">{{ Auth::user()->name }}</span></span><span class="avatar avatar-online"><img src="{{ asset('app-assets/images/portrait/small/avatar-s-19.png') }}" alt="avatar"><i></i></span></a>
                <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#"><i class="ft-user"></i> Edit Profile</a><a class="dropdown-item" href="#"><i class="ft-mail"></i> My Inbox</a><a class="dropdown-item" href="#"><i class="ft-check-square"></i> Task</a><a class="dropdown-item" href="#"><i class="ft-message-square"></i> Chats</a>
                  <div class="dropdown-divider"></div><a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="ft-power"></i> Logout</a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
                </div>
              </li>
              {{-- <li class="dropdown dropdown-notification nav-item"><a class="nav-link nav-link-label" href="#" data-toggle="dropdown"><i class="ficon ft-bell"></i><span class="badge badge-pill badge-default badge-danger badge-default badge-up badge-glow">5</span></a>
                <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                  <li class="dropdown-menu-header">
                    <h6 class="dropdown-header m-0"><span class="grey darken-2">Notifications</span></h6><span class="notification-tag badge badge-default badge-danger float-right m-0">5 New</span>
                  </li>
                  <li class="scrollable-container media-list w-100"><a href="javascript:void(0)">
                      <div class="media">
                        <div class="media-left align-self-center"><i class="ft-plus-square icon-bg-circle bg-cyan"></i></div>
                        <div class="media-body">
                          <h6 class="media-heading">You have new order!</h6>
                          <p class="notification-text font-small-3 text-muted">Lorem ipsum dolor sit amet, consectetuer elit.</p><small>
                            <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">30 minutes ago</time></small>
                        </div>
                      </div></a><a href="javascript:void(0)">
                      <div class="media">
                        <div class="media-left align-self-center"><i class="ft-download-cloud icon-bg-circle bg-red bg-darken-1"></i></div>
                        <div class="media-body">
                          <h6 class="media-heading red darken-1">99% Server load</h6>
                          <p class="notification-text font-small-3 text-muted">Aliquam tincidunt mauris eu risus.</p><small>
                            <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">Five hour ago</time></small>
                        </div>
                      </div></a><a href="javascript:void(0)">
                      <div class="media">
                        <div class="media-left align-self-center"><i class="ft-alert-triangle icon-bg-circle bg-yellow bg-darken-3"></i></div>
                        <div class="media-body">
                          <h6 class="media-heading yellow darken-3">Warning notifixation</h6>
                          <p class="notification-text font-small-3 text-muted">Vestibulum auctor dapibus neque.</p><small>
                            <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">Today</time></small>
                        </div>
                      </div></a><a href="javascript:void(0)">
                      <div class="media">
                        <div class="media-left align-self-center"><i class="ft-check-circle icon-bg-circle bg-cyan"></i></div>
                        <div class="media-body">
                          <h6 class="media-heading">Complete the task</h6><small>
                            <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">Last week</time></small>
                        </div>
                      </div></a><a href="javascript:void(0)">
                      <div class="media">
                        <div class="media-left align-self-center"><i class="ft-file icon-bg-circle bg-teal"></i></div>
                        <div class="media-body">
                          <h6 class="media-heading">Generate monthly report</h6><small>
                            <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">Last month</time></small>
                        </div>
                      </div></a></li>
                  <li class="dropdown-menu-footer"><a class="dropdown-item text-muted text-center" href="javascript:void(0)">Read all notifications</a></li>
                </ul>
              </li> --}}
            </ul>
          </div>
        </div>
      </div>
    </nav>